name: note_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase: ^9.0.2
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  cloud_firestore: ^3.1.7
  google_sign_in: ^5.2.3
  intl: ^0.17.0

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  shared_preferences: ^2.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-Regular.ttf
    - family: Lora
      fonts:
       - asset: fonts/Lora-Regular.ttf
    - family: SupermercadoOne
      fonts:
       - asset: fonts/SupermercadoOne-Regular.ttf
    - family: Comforter
      fonts:
       - asset: fonts/Comforter-Regular.ttf


  uses-material-design: true
